# Generated by Django 2.2.7 on 2020-01-06 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppDocente', '0001_initial'),
        ('GestionSistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantedocente',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionSistema.Docente'),
        ),
        migrations.AddField(
            model_name='estudiantedocente',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionSistema.Institucion'),
        ),
    ]
