# Generated by Django 2.2.7 on 2020-01-06 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppDocente', '0002_auto_20200106_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosticomedico',
            old_name='descripcion',
            new_name='diagnosticoMedicoDescripcion',
        ),
        migrations.RenameField(
            model_name='diagnosticomedico',
            old_name='opcion',
            new_name='diagnosticoMedicoOpcion',
        ),
        migrations.RenameField(
            model_name='diagnosticomedico',
            old_name='respuesta',
            new_name='diagnosticoMedicoRespuesta',
        ),
    ]
