# Generated by Django 2.2.7 on 2020-01-06 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppDocente', '0003_auto_20200106_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosticosindromico',
            old_name='descripcion',
            new_name='diagnostigoSindromicoDescripcion',
        ),
        migrations.RenameField(
            model_name='diagnosticosindromico',
            old_name='opcion',
            new_name='diagnostigoSindromicoOpcion',
        ),
        migrations.RenameField(
            model_name='diagnosticosindromico',
            old_name='respuesta',
            new_name='diagnostigoSindromicoRespuesta',
        ),
    ]
