# Generated by Django 2.2.7 on 2020-01-06 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppDocente', '0004_auto_20200106_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosticosindromico',
            old_name='diagnostigoSindromicoDescripcion',
            new_name='diagnosticoSindromicoDescripcion',
        ),
        migrations.RenameField(
            model_name='diagnosticosindromico',
            old_name='diagnostigoSindromicoOpcion',
            new_name='diagnosticoSindromicoOpcion',
        ),
        migrations.RenameField(
            model_name='diagnosticosindromico',
            old_name='diagnostigoSindromicoRespuesta',
            new_name='diagnosticoSindromicoRespuesta',
        ),
    ]
