# Generated by Django 2.2.7 on 2020-01-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDocente', '0005_auto_20200106_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticomedico',
            name='diagnosticoMedicoDescripcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosticomedico',
            name='diagnosticoMedicoOpcion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosticomedico',
            name='diagnosticoMedicoRespuesta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosticosindromico',
            name='diagnosticoSindromicoDescripcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosticosindromico',
            name='diagnosticoSindromicoOpcion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosticosindromico',
            name='diagnosticoSindromicoRespuesta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
