# Generated by Django 2.2.7 on 2020-01-07 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionSistema', '0003_auto_20200107_0700'),
        ('AppDocente', '0006_auto_20200106_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertoFicha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionSistema.Experto')),
                ('ficha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppDocente.EstudianteDocente')),
            ],
        ),
    ]
