# Generated by Django 2.2.7 on 2020-01-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDocente', '0007_expertoficha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantedocente',
            name='cedula',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
