# Generated by Django 2.2.7 on 2020-05-05 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionSistema', '0017_auto_20200430_2314'),
        ('AppDocente', '0008_auto_20200116_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaInformativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoFamilia', models.CharField(blank=True, max_length=50, null=True)),
                ('dinamicaFamiliar', models.CharField(blank=True, max_length=50, null=True)),
                ('antecedentesFPatologicos', models.CharField(blank=True, max_length=50, null=True)),
                ('emisionDiagnosticoSindromico', models.CharField(blank=True, max_length=50, null=True)),
                ('detalleDificultades', models.CharField(blank=True, max_length=1024, null=True)),
                ('diagnosticoMedico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppDocente.DiagnosticoMedico')),
                ('diagnosticoSindromico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppDocente.DiagnosticoSindromico')),
                ('dificultad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppDocente.Dificultad')),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionSistema.Docente')),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionSistema.Estudiante')),
            ],
        ),
    ]
