# Generated by Django 2.2.7 on 2020-05-06 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionSistema', '0017_auto_20200430_2314'),
        ('AppDocente', '0009_fichainformativa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpertoFicha',
            new_name='ExpertoFichaInformativa',
        ),
        migrations.RemoveField(
            model_name='estudiantedocente',
            name='diagnosticoMedico',
        ),
        migrations.RemoveField(
            model_name='estudiantedocente',
            name='diagnosticoSindromico',
        ),
        migrations.RemoveField(
            model_name='estudiantedocente',
            name='dificultad',
        ),
        migrations.RemoveField(
            model_name='estudiantedocente',
            name='docente',
        ),
        migrations.RemoveField(
            model_name='estudiantedocente',
            name='institucion',
        ),
        migrations.RemoveField(
            model_name='expertofichainformativa',
            name='ficha',
        ),
        migrations.AddField(
            model_name='expertofichainformativa',
            name='fichaInformativaDocente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppDocente.FichaInformativa'),
        ),
    ]
