# Generated by Django 2.2.7 on 2020-05-06 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppExperto', '0009_auto_20200506_2101'),
        ('AppDocente', '0010_auto_20200506_2101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstudianteDocente',
        ),
    ]
