# Generated by Django 2.2.7 on 2020-05-08 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppDocente', '0012_fichainformativadocente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertofichainformativa',
            name='fichaInformativaDocente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppDocente.FichaInformativaDocente'),
        ),
        migrations.DeleteModel(
            name='FichaInformativa',
        ),
    ]
