# Generated by Django 2.2.7 on 2020-05-08 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppDocente', '0013_auto_20200508_2240'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpertoFichaInformativa',
        ),
    ]
