# Generated by Django 2.2.7 on 2020-08-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, default='default-avatar.jpg', null=True, upload_to='img_perfil'),
        ),
    ]
