# Generated by Django 2.2.7 on 2020-08-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200813_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='estado',
            field=models.CharField(blank=True, default='nuevo', max_length=50, null=True),
        ),
    ]
