# Generated by Django 2.2.7 on 2020-01-07 00:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionSistema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='receptor',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='receptor',
            field=models.ManyToManyField(blank=True, null=True, related_name='receptor', to=settings.AUTH_USER_MODEL),
        ),
    ]
