# Generated by Django 2.2.7 on 2020-01-07 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionSistema', '0002_auto_20200107_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='receptor',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='receptor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receptor', to=settings.AUTH_USER_MODEL),
        ),
    ]
