# Generated by Django 2.2.7 on 2020-03-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionSistema', '0003_auto_20200107_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='experto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='img_perfil'),
        ),
    ]
