# Generated by Django 2.2.7 on 2020-04-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionSistema', '0004_experto_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experto',
            name='foto',
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='img_perfil'),
        ),
    ]
