# Generated by Django 2.2.7 on 2020-04-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionSistema', '0005_auto_20200401_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, default='default-foto.jpg', null=True, upload_to='img_perfil'),
        ),
    ]
