# Generated by Django 2.2.7 on 2020-04-14 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionSistema', '0007_auto_20200401_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.EmailField(blank=True, db_column='username', max_length=254, unique=True),
        ),
    ]
