# Generated by Django 2.2.7 on 2020-04-18 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionSistema', '0009_auto_20200414_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_user',
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fechaNacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(null=True, upload_to='img_perfil'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
