# Generated by Django 2.2.7 on 2020-04-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionSistema', '0012_auto_20200424_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(max_length=50),
        ),
    ]
