# Generated by Django 2.2.7 on 2020-04-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionSistema', '0013_auto_20200424_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.EmailField(error_messages={'invalid': 'Correo ya registrado.'}, max_length=254, unique=True),
        ),
    ]
