# Generated by Django 2.2.7 on 2020-04-30 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionSistema', '0015_auto_20200424_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('cedula', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('fechaNacimiento', models.DateField()),
                ('nivel', models.CharField(max_length=50)),
                ('institucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionSistema.Institucion')),
            ],
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
