# Generated by Django 2.2.7 on 2020-04-30 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionSistema', '0016_auto_20200430_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='apellidos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fechaNacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombres',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
