# Generated by Django 2.2.7 on 2020-05-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionSistema', '0017_auto_20200430_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default=models.EmailField(max_length=254, unique=True), max_length=254),
        ),
    ]
