# Generated by Django 2.2.7 on 2020-05-20 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionSistema', '0022_auto_20200513_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_online',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
