# Generated by Django 2.2.7 on 2020-07-16 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Canton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestLenguaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaNacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=100, null=True)),
                ('discapacidad', models.CharField(blank=True, max_length=100, null=True)),
                ('p1', models.CharField(blank=True, max_length=5, null=True)),
                ('p2', models.CharField(blank=True, max_length=5, null=True)),
                ('p3', models.CharField(blank=True, max_length=5, null=True)),
                ('p4', models.CharField(blank=True, max_length=5, null=True)),
                ('p5', models.CharField(blank=True, max_length=5, null=True)),
                ('p6', models.CharField(blank=True, max_length=5, null=True)),
                ('p7', models.CharField(blank=True, max_length=5, null=True)),
                ('p8', models.CharField(blank=True, max_length=5, null=True)),
                ('p9', models.CharField(blank=True, max_length=5, null=True)),
                ('p10', models.CharField(blank=True, max_length=5, null=True)),
                ('p11', models.CharField(blank=True, max_length=5, null=True)),
                ('p12', models.CharField(blank=True, max_length=5, null=True)),
                ('p13', models.CharField(blank=True, max_length=5, null=True)),
                ('p14', models.CharField(blank=True, max_length=5, null=True)),
                ('p15', models.CharField(blank=True, max_length=5, null=True)),
                ('p16', models.CharField(blank=True, max_length=5, null=True)),
                ('p17', models.CharField(blank=True, max_length=5, null=True)),
                ('p18', models.CharField(blank=True, max_length=5, null=True)),
                ('p19', models.CharField(blank=True, max_length=5, null=True)),
                ('p20', models.CharField(blank=True, max_length=5, null=True)),
                ('p21', models.CharField(blank=True, max_length=5, null=True)),
                ('p22', models.CharField(blank=True, max_length=5, null=True)),
                ('p23', models.CharField(blank=True, max_length=5, null=True)),
                ('p24', models.CharField(blank=True, max_length=5, null=True)),
                ('p25', models.CharField(blank=True, max_length=5, null=True)),
                ('p26', models.CharField(blank=True, max_length=5, null=True)),
                ('p27', models.CharField(blank=True, max_length=5, null=True)),
                ('p28', models.CharField(blank=True, max_length=5, null=True)),
                ('p29', models.CharField(blank=True, max_length=5, null=True)),
                ('p30', models.CharField(blank=True, max_length=5, null=True)),
                ('p31', models.CharField(blank=True, max_length=5, null=True)),
                ('p32', models.CharField(blank=True, max_length=5, null=True)),
                ('p33', models.CharField(blank=True, max_length=5, null=True)),
                ('p34', models.CharField(blank=True, max_length=5, null=True)),
                ('p35', models.CharField(blank=True, max_length=5, null=True)),
                ('p36', models.CharField(blank=True, max_length=5, null=True)),
                ('p37', models.CharField(blank=True, max_length=5, null=True)),
                ('p38', models.CharField(blank=True, max_length=5, null=True)),
                ('canton', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='automata.Canton')),
            ],
        ),
        migrations.CreateModel(
            name='ResumenExperto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='audio/')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
