# Generated by Django 2.2.7 on 2020-07-09 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testlenguaje',
            name='discapacidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
