# Generated by Django 2.2.7 on 2020-08-01 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docente', '0001_initial'),
        ('core', '0001_initial'),
        ('representante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertoFichaInformativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Estudiante')),
                ('experto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Experto')),
                ('fichaInformativaDocente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docente.FichaInformativaDocente')),
                ('fichaInformativaRepresentante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='representante.FichaInformativaRepresentante')),
            ],
        ),
    ]
