# Generated by Django 2.2.7 on 2020-07-16 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppExperto', '0001_initial'),
        ('AppRepresentante', '0001_initial'),
        ('GestionSistema', '0001_initial'),
        ('AppDocente', '0002_auto_20200715_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertofichainformativa',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionSistema.Estudiante'),
        ),
        migrations.AddField(
            model_name='expertofichainformativa',
            name='experto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionSistema.Experto'),
        ),
        migrations.AddField(
            model_name='expertofichainformativa',
            name='fichaInformativaDocente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppDocente.FichaInformativaDocente'),
        ),
        migrations.AddField(
            model_name='expertofichainformativa',
            name='fichaInformativaRepresentante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppRepresentante.FichaInformativaRepresentante'),
        ),
    ]
