# Generated by Django 2.2.7 on 2020-01-09 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppExperto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='receptor1',
            new_name='fichaEstudiante',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='receptor2',
        ),
    ]
