# Generated by Django 2.2.7 on 2020-06-23 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppRepresentante', '0001_initial'),
        ('AppDocente', '0002_auto_20200623_0009'),
        ('GestionSistema', '0001_initial'),
        ('AppExperto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expertofichainformativa',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionSistema.Estudiante'),
        ),
        migrations.AddField(
            model_name='expertofichainformativa',
            name='experto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionSistema.Experto'),
        ),
        migrations.AddField(
            model_name='expertofichainformativa',
            name='fichaInformativaDocente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppDocente.FichaInformativaDocente'),
        ),
        migrations.AddField(
            model_name='expertofichainformativa',
            name='fichaInformativaRepresentante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppRepresentante.FichaInformativaRepresentante'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='emisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentario',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionSistema.Estudiante'),
        ),
    ]
