# Generated by Django 2.2.7 on 2020-01-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppExperto', '0002_auto_20200109_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
