# Generated by Django 2.2.7 on 2020-01-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppExperto', '0004_auto_20200116_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='nombreEmisor',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
