# Generated by Django 2.2.7 on 2020-01-16 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppExperto', '0005_comentario_nombreemisor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='nombreEmisor',
            new_name='usernameEmisor',
        ),
    ]
