# Generated by Django 2.2.7 on 2020-04-19 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppExperto', '0006_auto_20200116_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='usernameEmisor',
            new_name='useEmisor',
        ),
    ]
