# Generated by Django 2.2.7 on 2020-04-19 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppExperto', '0007_auto_20200419_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='useEmisor',
            new_name='usernameEmisor',
        ),
    ]
