# Generated by Django 2.2.7 on 2020-05-08 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionSistema', '0017_auto_20200430_2314'),
        ('AppDocente', '0014_delete_expertofichainformativa'),
        ('AppRepresentante', '0006_auto_20200508_2254'),
        ('AppExperto', '0009_auto_20200506_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertoFichaInformativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionSistema.Experto')),
                ('fichaInformativaDocente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppDocente.FichaInformativaDocente')),
                ('fichaInformativaRepresentante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppRepresentante.FichaInformativaRepresentante')),
            ],
        ),
    ]
