# Generated by Django 2.2.7 on 2020-05-24 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionSistema', '0023_usuario_is_online'),
        ('AppExperto', '0010_expertofichainformativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertofichainformativa',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionSistema.Estudiante'),
        ),
    ]
