# Generated by Django 2.2.7 on 2020-08-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200731_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
