# Generated by Django 2.2.7 on 2020-08-01 01:42

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticoMedico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosticoMedicoRespuesta', models.CharField(blank=True, max_length=50, null=True)),
                ('diagnosticoMedicoOpcion', models.CharField(blank=True, max_length=50, null=True)),
                ('diagnosticoMedicoDescripcion', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticoSindromico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosticoSindromicoRespuesta', models.CharField(blank=True, max_length=50, null=True)),
                ('diagnosticoSindromicoOpcion', models.CharField(blank=True, max_length=50, null=True)),
                ('diagnosticoSindromicoDescripcion', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dificultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_prenatal', models.CharField(max_length=50)),
                ('descripcion_prenatal', models.CharField(blank=True, max_length=50, null=True)),
                ('respuesta_perinatal', models.CharField(max_length=50)),
                ('descripcion_perinatal', models.CharField(blank=True, max_length=50, null=True)),
                ('respuesta_postnatal', models.CharField(max_length=50)),
                ('descripcion_postnatal', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstudianteTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FichaInformativaDocente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoFamilia', models.CharField(blank=True, max_length=50, null=True)),
                ('tipoFamiliaDescripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('dinamicaFamiliar', models.CharField(blank=True, max_length=50, null=True)),
                ('antecedentesFPatologicos', models.CharField(blank=True, max_length=50, null=True)),
                ('antecedentesFPatologicosDescripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('emisionDiagnosticoSindromico', models.CharField(blank=True, max_length=50, null=True)),
                ('emisionDiagnosticoSindromicoDetalle', models.CharField(blank=True, max_length=500, null=True)),
                ('dificultadesAula', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('cognicion', 'Cognición '), ('lenguaje', 'Lenguaje'), ('motricidadgruesa', 'Motricidad gruesa'), ('motricidadfina', 'Motricidad fina'), ('social', 'Social'), ('autonomia', 'Autonomía ')], max_length=100, null=True)),
                ('detalleDificultades', models.CharField(blank=True, max_length=1024, null=True)),
                ('diagnosticoMedico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docente.DiagnosticoMedico')),
                ('diagnosticoSindromico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docente.DiagnosticoSindromico')),
                ('dificultad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docente.Dificultad')),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Docente')),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Estudiante')),
            ],
        ),
    ]
