# Generated by Django 2.2.7 on 2020-07-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200630_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img_chat'),
        ),
    ]
