# Generated by Django 2.2.7 on 2020-07-01 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_room_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='img',
        ),
    ]
