# Generated by Django 2.2.7 on 2020-07-13 22:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_room_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='messages',
            field=models.ManyToManyField(blank=True, null=True, to='chat.Message'),
        ),
        migrations.AlterField(
            model_name='room',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
