# Generated by Django 2.2.7 on 2020-06-23 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticoMedico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosticoMedicoRespuesta', models.CharField(blank=True, max_length=50, null=True)),
                ('diagnosticoMedicoOpcion', models.CharField(blank=True, max_length=50, null=True)),
                ('diagnosticoMedicoDescripcion', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dificultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_prenatal', models.CharField(max_length=50)),
                ('descripcion_prenatal', models.CharField(blank=True, max_length=50, null=True)),
                ('respuesta_perinatal', models.CharField(max_length=50)),
                ('descripcion_perinatal', models.CharField(blank=True, max_length=50, null=True)),
                ('respuesta_postnatal', models.CharField(max_length=50)),
                ('descripcion_postnatal', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FichaInformativaRepresentante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoFamilia', models.CharField(blank=True, max_length=50, null=True)),
                ('dinamicaFamiliar', models.CharField(blank=True, max_length=50, null=True)),
                ('antecedentesFPatologicos', models.CharField(blank=True, max_length=50, null=True)),
                ('detalleDificultades', models.CharField(blank=True, max_length=1024, null=True)),
                ('diagnosticoMedico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppRepresentante.DiagnosticoMedico')),
                ('dificultad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppRepresentante.Dificultad')),
            ],
        ),
    ]
