# Generated by Django 2.2.7 on 2020-01-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstudianteRepresentante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('cedula', models.CharField(blank=True, max_length=50, null=True)),
                ('fechaNacimiento', models.DateField()),
                ('nivelCursa', models.CharField(max_length=50)),
                ('tipoFamilia', models.CharField(max_length=50)),
                ('dinamicaFamiliar', models.CharField(max_length=50)),
                ('antecedentesFPatologicos', models.CharField(blank=True, max_length=50, null=True)),
                ('diagnosticoRecibido', models.CharField(blank=True, max_length=50, null=True)),
                ('detalleDificultades', models.CharField(max_length=1024)),
            ],
        ),
    ]
