# Generated by Django 2.2.7 on 2020-01-06 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppRepresentante', '0001_initial'),
        ('GestionSistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudianterepresentante',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instituciones', to='GestionSistema.Institucion'),
        ),
        migrations.AddField(
            model_name='estudianterepresentante',
            name='representante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionSistema.Representante'),
        ),
    ]
