# Generated by Django 2.2.7 on 2020-01-16 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppRepresentante', '0002_auto_20200106_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticoMedico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosticoMedicoRespuesta', models.CharField(blank=True, max_length=50, null=True)),
                ('diagnosticoMedicoOpcion', models.CharField(blank=True, max_length=50, null=True)),
                ('diagnosticoMedicoDescripcion', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dificultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_prenatal', models.CharField(max_length=50)),
                ('descripcion_prenatal', models.CharField(blank=True, max_length=50, null=True)),
                ('respuesta_perinatal', models.CharField(max_length=50)),
                ('descripcion_perinatal', models.CharField(blank=True, max_length=50, null=True)),
                ('respuesta_postnatal', models.CharField(max_length=50)),
                ('descripcion_postnatal', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='estudianterepresentante',
            name='diagnosticoRecibido',
        ),
        migrations.AlterField(
            model_name='estudianterepresentante',
            name='cedula',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='estudianterepresentante',
            name='detalleDificultades',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='estudianterepresentante',
            name='dinamicaFamiliar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='estudianterepresentante',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionSistema.Institucion'),
        ),
        migrations.AlterField(
            model_name='estudianterepresentante',
            name='tipoFamilia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='estudianterepresentante',
            name='diagnosticoMedico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppRepresentante.DiagnosticoMedico'),
        ),
        migrations.AddField(
            model_name='estudianterepresentante',
            name='dificultad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppRepresentante.Dificultad'),
        ),
    ]
