# Generated by Django 2.2.7 on 2020-05-08 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionSistema', '0017_auto_20200430_2314'),
        ('AppRepresentante', '0004_representante_expertoficha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudianterepresentante',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='estudianterepresentante',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='estudianterepresentante',
            name='fechaNacimiento',
        ),
        migrations.RemoveField(
            model_name='estudianterepresentante',
            name='institucion',
        ),
        migrations.RemoveField(
            model_name='estudianterepresentante',
            name='nivelCursa',
        ),
        migrations.RemoveField(
            model_name='estudianterepresentante',
            name='nombres',
        ),
        migrations.AddField(
            model_name='estudianterepresentante',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionSistema.Estudiante'),
        ),
        migrations.CreateModel(
            name='FichaInformativaRepresentante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoFamilia', models.CharField(blank=True, max_length=50, null=True)),
                ('dinamicaFamiliar', models.CharField(blank=True, max_length=50, null=True)),
                ('antecedentesFPatologicos', models.CharField(blank=True, max_length=50, null=True)),
                ('detalleDificultades', models.CharField(blank=True, max_length=1024, null=True)),
                ('diagnosticoMedico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppRepresentante.DiagnosticoMedico')),
                ('dificultad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppRepresentante.Dificultad')),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionSistema.Estudiante')),
                ('representante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionSistema.Representante')),
            ],
        ),
    ]
