# Generated by Django 2.2.7 on 2020-05-08 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppRepresentante', '0005_auto_20200508_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representante_expertoficha',
            name='experto',
        ),
        migrations.RemoveField(
            model_name='representante_expertoficha',
            name='ficha',
        ),
        migrations.DeleteModel(
            name='EstudianteRepresentante',
        ),
        migrations.DeleteModel(
            name='Representante_ExpertoFicha',
        ),
    ]
